### PR TITLE
Add support for multi-module projects and com.android.test modules.

### PR DESCRIPTION
**Pull request by mcumings**
The DDMS bridge does not seem to operate when destroyed and re-opened.
As a result, multi-module projects were unable to leverage this plugin
to record logcat data.  This change introduces an AdbBridgeManager
singleton to manage DDMS in a single location and spanning the lifecycle
of the build.  This also improves behavior when running Gradle with
--parallel.

As a result of the above, the mechanism used to start the recording
has transitioned from a task dependency to a "doFirst" closure call.
The finalizing LogCatPrinterTask retains the responsibility for
closing out the recording.

Also, expanded the use of this plugin to com.android.test modules
in addition to application and library modules.

### CODE REVIEW

**Comment by mcumings** [comment]
Is this project still being maintained?  The contributors doc specifies a target of 3 business days for first contact and it has nearly been 3 times that.  Just pinging to see if this got lost in the noise...

**Comment by mcumings** [comment]
@RomainPiel - I'm trying a direct ping in case you missed this.  Thanks in advance!

**Comment by AaronRandall** [comment]
Hi Mike,

Apologies for the delay getting back to you. Unfortunately we are no longer maintaining this project (I've updated CONTRIBUTING.md and the repo description to reflect this).

Please fork the repo if you require this project going forward.

Thanks,

Aaron

**Comment by mcumings** [comment]
Okay, thanks for letting me know.

**Pull request closed without merging**
